from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from app.models.report import Report
from app.schemas.report import ReportRead
import uuid

class ReportRepository:
    """Database operations for reports"""
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create(self, report_data: dict) -> Report:
        """Create a new report"""
        report = Report(**report_data)
        self.db.add(report)
        await self.db.flush()
        await self.db.refresh(report)
        return report

    async def get_by_id(self, report_id: uuid.UUID) -> Report | None:
        """Get report by ID"""
        result = await self.db.execute(
            select(Report).where(Report.id == report_id)
        )
        return result.scalar_one_or_none()

    async def get_all(self, skip: int = 0, limit: int = 100) -> list[Report]:
        """Get all reports"""
        result = await self.db.execute(
            select(Report).offset(skip).limit(limit)
        )
        return list(result.scalars().all())

    async def get_by_exhibition(self, exhibition_id: uuid.UUID) -> list[Report]:
        """Get all reports for an exhibition"""
        result = await self.db.execute(
            select(Report).where(Report.exhibition_id == exhibition_id)
        )
        return list(result.scalars().all())

    async def get_by_user(self, user_id: uuid.UUID) -> list[Report]:
        """Get all reports generated by a user"""
        result = await self.db.execute(
            select(Report).where(Report.generated_by_id == user_id)
        )
        return list(result.scalars().all())

    async def delete(self, report_id: uuid.UUID) -> bool:
        """Delete a report"""
        report = await self.get_by_id(report_id)
        if not report:
            return False
        await self.db.delete(report)
        return True
